# Generated by Django 2.2 on 2022-07-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('name_ru', 'cost'), 'verbose_name': 'Блюда', 'verbose_name_plural': 'Разделы меню'},
        ),
    ]
